// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2QUYfxYgT8wIryPe9WWkYUcs7tUrxvyY',
    appId: '1:165485650711:android:5029adc842d523980e8d52',
    messagingSenderId: '165485650711',
    projectId: 'carservice-93787',
    storageBucket: 'carservice-93787.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdPVHtExrFy38PVpNPW94aWL0TrSRSX3g',
    appId: '1:165485650711:ios:4f0c6c7d520179d50e8d52',
    messagingSenderId: '165485650711',
    projectId: 'carservice-93787',
    storageBucket: 'carservice-93787.appspot.com',
    androidClientId: '165485650711-chot6eaom44fo2cakebcepp3gdm4cgq1.apps.googleusercontent.com',
    iosClientId: '165485650711-2va3ck8ng2t93it9tus5sgiq254910ls.apps.googleusercontent.com',
    iosBundleId: 'com.example.carservice',
  );

}